name: Backfill Bars Function

on:
  push:
    paths:
      - backfill_bars/**

env:
  FUNCTION: backfill_bars

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - uses: action/checkout@v1
      - name: GCP Authenticate
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy to GCP
        uses: actions/gcloud/cli@master
        with:
          args: |
            beta functions \
            list --project pathfinder--staging
