name: Test1

on: push

env:
  TEST: test1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          case "${{ github.ref }}" in
            refs/heads/master)
              export STAGE=prod
              ;;
            refs/heads/staging)
              export STAGE=staging
              ;;
            *)
              exit 1
              ;;
          esac
          echo $STAGE
      - run: echo $STAGE
