name: Test1

on: push

env:
  TEST: test1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: |
            gcloud beta functions list --quiet \
            --project pathfinder--staging \
