name: Test1

on: push

env:
  TEST: test1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - uses: actions/checkout@v1
      - run: ls
      - run: bash .github/workflows/set_stage.sh ${{ github.ref }}
        id: stage
      - run: echo $STAGE
      - run: echo "${{ steps.stage.auth }}"
