name: Test1

on: push

env:
  TEST: test1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - uses: actions/checkout@v1
      - name: GCP Authenticate
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy to GCP
        uses: actions/gcloud/cli@master
        with:
          args: |
            beta functions \
            list --project pathfinder--staging \
            --quiet
